apiVersion: v1
kind: Pod
metadata:
  name: evil-hostpath
  namespace: demo-app
spec:
  containers:
  - name: evil
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: host
      mountPath: /host
  volumes:
  - name: host
    hostPath:
      path: /
